config/routes.rb
# frozen_string_literal: true

require "sidekiq/web"

Rails.application.routes.draw do
  mount RailsAdmin::Engine => "/admin", :as => "rails_admin"
  authenticate :user, lambda { |u| u.is_admin? } do
    mount Sidekiq::Web => "/sidekiq"
    mount ActiveAnalytics::Engine, at: "analytics"
    mount MaintenanceTasks::Engine => "/maintenance_tasks"
  end

  devise_for :users, controllers: {omniauth_callbacks: "users/omniauth_callbacks"}
  resources :podcasts, only: %i[index show] do
    get :search, on: :collection
    get "subscribers", to: "podcasts#subscribers"
    resources :episodes, only: %i[show index] do
      resources :comments
      patch :like, to: "episodes#like"
      patch :dislike, to: "episodes#dislike"
      patch :marked_as_listened, to: "episodes#marked_as_listened"
      patch :marked_as_unlistened, to: "episodes#marked_as_unlistened"
    end
  end

  resources :dashboard, only: [:index]

  resources :users do
    member do
      get :following, :followers
      get :email_confirmation
      post :allow_email_confirmation
      post :deny_email_confirmation
    end
    collection do
      get :tigers
    end
  end

  resources :relationships, only: %i[create destroy]
  resources :subscriptions, only: %i[index show]
  resources :categories, only: %i[index show]
  resources :activities, only: %i[index], path: "feed"
  resources :discovers, only: %i[index], path: "discover" do
    get :advice, on: :collection
    get :all_responses, on: :collection
  end

  namespace :host do
    resources :podcasts do
      get :episodes
      resources :episodes, only: %i[show index]
    end
  end

  root "home#index"
end

app/models/user.rb
# frozen_string_literal: true

require "open-uri"

class User < ApplicationRecord
  devise :database_authenticatable, :registerable, :trackable,
    :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:spotify]

  has_many :subscriptions, dependent: :destroy
  has_many :podcasts, through: :subscriptions, source: :podcast
  has_many :user_listened_episodes, class_name: "UserListenedEpisode"
  has_many :listened_episodes, through: :user_listened_episodes, source: :episode

  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy

  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  has_many :activities, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :openai_requests

  has_many :own_shows, class_name: "Podcast", foreign_key: "owner_id"

  after_create :send_new_user_email, :create_broadcast_activity

  extend FriendlyId
  friendly_id :slug_candidates, use: :slugged

  def self.from_omniauth(auth)
    user = User.find_by(email: auth.info.email)

    if user.present?
      user.update!(
        image_url: User.image(auth),
        external_url: auth.info.external_urls["spotify"]
      )
      user.display_name = auth.info.display_name unless user.update_manuelly
    else
      user = User.new
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.display_name = auth.info.display_name
      user.external_url = auth.info.external_urls["spotify"]
      user.image_url = image(auth)
      user.password = Devise.friendly_token[0, 20]
      user.daily_openai_credit = 10

      user.save!
    end

    FetchUserPodcasts.perform_async(user.id, auth)

    user
  end

  def display_email
    if allow_email_confirmation
      email
    else
      "Hidden"
    end
  end

  def is_admin?
    email == ENV["ADMIN_EMAIL"]
  end

  def nickname
    display_name.present? ? display_name : email.split("@").first
  end

  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
    Activity.create!(activatable: Followable.create(follower_id: id, followed_id: other_user.id, action: "followed"), user_id: id)
  end

  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
    Activity.create!(activatable: Followable.create(follower_id: id, followed_id: other_user.id, action: "unfollowed"), user_id: id)
  end

  def following?(other_user)
    following.include?(other_user)
  end

  def feed
    following_ids = "SELECT followed_id FROM relationships
                     WHERE  follower_id = :user_id"
    Subscription.where("user_id IN (#{following_ids})", user_id: id)
  end

  def activity_feed
    following_ids = "SELECT followed_id FROM relationships
                     WHERE  follower_id = :user_id"
    Activity.where("user_id IN (#{following_ids})", user_id: id)
      .or(Activity.broadcastables.where.not(user_id: id))
      .order(created_at: :desc)
  end

  def self.image(auth)
    return nil if auth.info.images.empty?

    profile_image_url = auth.info.images.last.url

    begin
      URI.parse(profile_image_url).open
      profile_image_url
    rescue
      nil
    end
  end

  def send_new_user_email
    UserMailer.new_user(self).deliver_now
  end

  def create_broadcast_activity
    Activity.create!(activatable: Broadcastable.new(action: "new_user_has_joined"),
      user_id: id)
  end

  def slug_candidates
    [
      :sluggified_nickname,
      [:sluggified_nickname, SecureRandom.hex(2)]
    ]
  end

  def can_openai?
    daily_openai_credit > 0
  end

  def categories_count
    query = "select c.name, count(*) as count from subscriptions as u
      inner join podcasts as p on u.podcast_id = p.id
      inner join genres as g on g.podcast_id = p.id
      inner join categories as c on g.category_id = c.id
      where u.user_id = #{id}
      group by c.name
      order by count desc"

    results = ActiveRecord::Base.connection.execute(query)

    if results.present?
      results.to_a.first(3).map { |r| r["name"] }
    end
  end

  def description
    "subscribes #{subscriptions.count} podcasts"
  end

  private

  def sluggified_nickname
    nickname.parameterize
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  skip_before_action :verify_authenticity_token, only: :spotify

  def spotify
    @user = User.from_omniauth(request.env["omniauth.auth"])

    sign_in_and_redirect @user
  end

  def failure
    flash[:warn] = "🥺 This is a private beta project. Access to your Spotify account must be granted to continue."
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:show]
  before_action :find_user, except: [:index]
  layout "email_confirmation_layout", only: [:email_confirmation]

  def index
    users = User.where.not(id: current_user.id).to_a
    @users = users.sort_by! { |user| user.podcasts.count }.reverse
  end

  def show
    @subscriptions = @user.subscriptions
  end

  def following
    @title = "Following"
    @users = @user.following
  end

  def followers
    @title = "Followers"
    @users = @user.followers
  end

  def email_confirmation
  end

  def allow_email_confirmation
    @user.update(allow_email_usage_at: Time.now, tmp_email: nil)

    redirect_to activities_path
  end

  def deny_email_confirmation
    @user.update(allow_email_usage_at: nil, tmp_email: tmp_email_generator)

    redirect_to activities_path
  end

  def edit
  end

  def update
    @user.display_name = user_params["display_name"]
    @user.update_manuelly = true
    @user.save!

    flash[:warn] = "User updated"
    redirect_to @user
  end

  private

  def find_user
    @user = User.friendly.find(params[:id])
  end

  def tmp_email_generator
    SecureRandom.hex(10) + "@example.com"
  end

  def user_params
    params.require(:user).permit!
  end
end

app/views/users/_follower.html.erb
<%= turbo_frame_tag "#{dom_id(user)}_follows", class: "flex space-x-12" do %>
  <div class="flex items-center space-x-12">
    <%= link_to following_user_path(@user), class: 'flex flex-col items-center hover:underline', 'data-turbo-frame': "_top" do %>
      <span class="font-bold"><%= user.following.count %></span>
      <span class="text-xs font-medium text-gray-400">Following</span>
    <% end %>
    <span class="w-1 h-1 rounded-full bg-gray-400 block"></span>
    <%= link_to followers_user_path(@user), class: 'flex flex-col items-center hover:underline', 'data-turbo-frame': "_top" do %>
      <span class="font-bold"><%= user.followers.count %></span>
      <span class="text-xs font-medium text-gray-400">Followers</span>
    <% end %>
  </div>
  <div>
    <% if current_user != user %>
      <% if current_user.following?(user) %>
        <%= form_for(current_user.active_relationships.find_by(followed_id: user.id),
                    html: { method: :delete }) do |f| %>
          <%= f.submit "Unfollow", class: "bg-white border border-primary hover:bg-secondary cursor-pointer text-primary font-bold py-2 px-4 rounded-full" %>
        <% end %>
      <% else %>
        <%= form_for(current_user.active_relationships.build, id: "#{dom_id(current_user)}_follow_form") do |f| %>
          <div><%= hidden_field_tag :followed_id, user.id %></div>
          <%= f.submit "Follow", class: "bg-primary border border-transparent hover:bg-secondary hover:text-primary cursor-pointer text-white font-bold py-2 px-6 rounded-full" %>
        <% end %>
      <% end %>    
    <% end %> 
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="w-full">
  <div class="flex items-center justify-between">
    <h1 class="text-4xl font-bold">Edit Profile</h1>
  </div>
  <section class="p-2 py-24 mt-10 bg-white rounded-xl">
    <%= form_with model: @user do |form| %>
      <div class="p-4">
        <%= form.label "Username", class: "block text-xs font-medium text-gray-700" %>
        <%= form.text_field :display_name, class: "border-gray-200 rounded-md shadow-sm sm:text-sm" %>
        <%= form.submit class: "mt-5 inline-block rounded border border-indigo-600 bg-indigo-600 px-12 py-2 text-sm font-medium text-white hover:bg-transparent hover:text-indigo-600 focus:outline-none focus:ring active:text-indigo-500" %>
      </div>
    <% end %>
  </section>
</div>

app/views/users/email_confirmation.html.erb
<section class="py-20 bg-white">
    <div class="px-4 mx-auto text-center max-w-7xl sm:px-6 lg:px-8">
        <p class="tracking-tight text-gray-900">
          Create an account for Podiscover using your <span class="text-[#1db954]">Spotify</span> email address <span class="font-extrabold"> <%= @user.email %></span>
        </p>
        <div class="max-w-md mx-auto mt-3 text-base text-gray-500">
          <div>
            <span class="font-extrabold">Name:</span> <%= @user.display_name %> 
          </div>
          <div>
            <span class="font-extrabold">Email:</span> <%= @user.email %> 
          </div>
        </div>
        <div class="flex justify-center mt-8 space-x-3">
        <%= button_to 'Share my email address', allow_email_confirmation_user_path(@user), data: { turbo: "false" }, class: "inline-flex items-center justify-center px-5 py-3 text-base font-medium text-white bg-green-600 border border-transparent rounded-md shadow hover:bg-indigo-700" %>
        <%= button_to 'Hide my email address', deny_email_confirmation_user_path(@user), data: { turbo: "false" }, class: "inline-flex items-center justify-center px-5 py-3 text-base font-medium text-white bg-red-600 border border-transparent rounded-md shadow hover:bg-indigo-700" %>
        </div>
    </div>
</section>

app/views/users/followers.html.erb
<div class="flex flex-col w-full gap-8">
  <div class="flex items-center justify-between">
    <h1 class="text-4xl font-bold">Follower</h1>
  </div>

  <% if @users.empty? %>
    <div class="flex flex-col items-center justify-center p-12 bg-white rounded-xl">
      <p class="text-gray-500">😢 No one follows you</p>
      <%= image_tag "not-found.svg", class:"my-12" %>
      <%=  link_to 'Find some cool people 🥳', users_path, class:"bg-primary text-white rounded-full px-6 py-2" %>
    </div>
  <% end %>

  <div class="grid grid-cols-2 gap-4 lg:grid-cols-4">
    <%= render @users %>
  </div>
</div>

app/views/users/following.html.erb
<div class="flex flex-col w-full gap-8">
  <div class="flex items-center justify-between">
    <h1 class="text-4xl font-bold">Following</h1>
  </div>

  <% if @users.empty? %>
    <div class="flex flex-col items-center justify-center p-12 bg-white rounded-xl">
      <p class="text-gray-500">You don't follow no one 🧐</p>
      <%= image_tag "not-found.svg", class:"my-12" %>
      <%=  link_to 'Find some cool people 🥳', users_path, class:"bg-primary text-white rounded-full px-6 py-2" %>
    </div>
  <% end %>

  <div class="grid grid-cols-2 gap-4 lg:grid-cols-4">
    <%= render @users %>
  </div>
</div>

app/views/users/index.html.erb
<div class="flex flex-col gap-8">
  <div class="flex items-center justify-between">
    <h1 class="text-4xl font-bold">Community (<%= @users.count %>)</h1>
  </div>
  <div id="users" class="grid min-w-full gap-4 2xl:grid-cols-4 xl:grid-cols-4 lg:grid-cols-2">
    <%= render @users %>
  </div>
</div>

app/views/users/show.html.erb
<%  content_for :og_header do %>
  <%= tag(:meta, name: "twitter:card", content: "summary") %>
  <%= tag(:meta, name: "twitter:title", content: @user.nickname) %>
  <%= tag(:meta, name: "twitter:description", content: @user.description) %>
  <%= tag(:meta, name: "twitter:image", content: @user.image_url) %>
  <%= tag(:meta, property: "og:title", content: @user.nickname) %>
  <%= tag(:meta, property: "og:description", content: @user.description) %>
  <%= tag(:meta, property: "og:image", content: @user.image_url) %>
  <%= tag(:meta, property: "og:url", content: user_path(@user)) %>
<% end %>

<div class="w-full">
  <% if flash[:warn] %>
    <div class="p-4 mb-4 text-sm text-yellow-700 bg-yellow-100 rounded-lg dark:bg-yellow-200 dark:text-yellow-800" role="alert">
      <span class="font-medium"><%= flash[:warn] %></span>
    </div>
  <% end %>
  <div class="flex items-center justify-between py-4 pr-8 space-x-12 bg-white lg:ml-20 rounded-xl">
    <div class="flex items-center">
      <div class="flex w-20 h-20 lg:w-40 lg:h-40 lg:relative translate-x-1/4 lg:-translate-x-1/2">
        <div class="flex w-20 h-20 lg:w-40 lg:h-40">
          <% if @user.image_url.present? %>
            <%= image_tag @user.image_url, class: "w-40 w-40 rounded-full border border-gray-100 bg-white shadow-sm" %>
          <% else %>
            <%= image_tag "default.png", class: "w-40 w-40 rounded-full border border-gray-100 bg-whiteshadow-sm" %>
          <% end %>
        </div>
      </div>
      <div class="flex flex-col ml-12 lg:-ml-12 h-max justify-evenly">
        <div class="text-lg font-bold ">
          <%= @user.nickname %>
          <% if @user == current_user %>
            <%= link_to  "Edit Profile", edit_user_path(@user), class: "text-sm font-thin text-gray-400 ml-10" %>
          <% end %>
        </div>
        <div class="text-gray-400">
          subscribes <%= @user.podcasts.count %> podcasts
        </div>
        <div class="mt-5">
          <% @user.categories_count.each do |category| %>
            <%= render(CategoriesComponent.new(name: category)) %>
          <% end %>
        </div>
      </div>
    </div>
    <% if current_user %>
      <div class="hidden lg:flex">
        <%= render partial: 'users/follower', locals: { user: @user } %>
      </div>
    <% end %>
  </div>

  <%= turbo_stream_from "subscriptions" %>
  <div
    id="subscriptions"
    class="grid min-w-full gap-4 mt-4 2xl:grid-cols-6 xl:grid-cols-4 lg:grid-cols-2"
  >
    <%= render @subscriptions %>
  </div>
</div>