config/routes.rb
# frozen_string_literal: true

require "sidekiq/web"

Rails.application.routes.draw do
  mount RailsAdmin::Engine => "/admin", :as => "rails_admin"
  authenticate :user, lambda { |u| u.is_admin? } do
    mount Sidekiq::Web => "/sidekiq"
    mount ActiveAnalytics::Engine, at: "analytics"
    mount MaintenanceTasks::Engine => "/maintenance_tasks"
  end

  devise_for :users, controllers: {omniauth_callbacks: "users/omniauth_callbacks"}
  resources :podcasts, only: %i[index show] do
    get :search, on: :collection
    get "subscribers", to: "podcasts#subscribers"
    resources :episodes, only: %i[show index] do
      resources :comments
      patch :like, to: "episodes#like"
      patch :dislike, to: "episodes#dislike"
      patch :marked_as_listened, to: "episodes#marked_as_listened"
      patch :marked_as_unlistened, to: "episodes#marked_as_unlistened"
    end
  end

  resources :dashboard, only: [:index]

  resources :users do
    member do
      get :following, :followers
      get :email_confirmation
      post :allow_email_confirmation
      post :deny_email_confirmation
    end
    collection do
      get :tigers
    end
  end

  resources :relationships, only: %i[create destroy]
  resources :subscriptions, only: %i[index show]
  resources :categories, only: %i[index show]
  resources :activities, only: %i[index], path: "feed"
  resources :discovers, only: %i[index], path: "discover" do
    get :advice, on: :collection
    get :all_responses, on: :collection
  end

  namespace :host do
    resources :podcasts do
      get :episodes
      resources :episodes, only: %i[show index]
    end
  end

  root "home#index"
end

app/views/shared/_footer.html.erb
<div class="flex flex-col space-x-4 space-y-5">
	<div>
		<% if user_signed_in? %>
			<%= button_to "Logout", destroy_user_session_path, method: :delete, class:"text-red-400" %>
		<% end %>
	</div>
	<div class="flex items-center">
		<svg class="flex-shrink-0 width="30" height="30" viewBox="0 0 500 500" fill="none" xmlns="http://www.w3.org/2000/svg">
			<path d="M197.86 70.4884C197.866 72.7745 198.322 75.0376 199.202 77.1475C200.082 79.2576 201.37 81.1736 202.99 82.786C204.611 84.3987 206.534 85.6762 208.648 86.5456C210.763 87.4151 213.028 87.8595 215.314 87.8534C247.637 87.7686 278.67 100.527 301.585 123.324C324.501 146.118 337.422 177.084 337.506 209.407C337.591 241.729 324.833 272.762 302.037 295.678C279.241 318.593 248.277 331.515 215.954 331.6C211.367 331.657 206.988 333.522 203.769 336.792C200.55 340.059 198.751 344.467 198.763 349.056C198.775 353.643 200.597 358.04 203.833 361.291C207.07 364.543 211.458 366.385 216.045 366.42C236.623 366.364 256.987 362.259 275.978 354.335C294.969 346.409 312.212 334.822 326.723 320.234C341.237 305.644 352.733 288.341 360.558 269.31C368.381 250.277 372.381 229.892 372.327 209.315C372.273 188.737 368.167 168.373 360.243 149.382C352.317 130.393 340.731 113.149 326.143 98.6368C311.555 84.1251 294.25 72.6273 275.219 64.804C256.188 56.9794 235.801 52.9799 215.223 53.034C210.606 53.0461 206.183 54.892 202.927 58.1653C199.67 61.4387 197.848 65.8717 197.86 70.4889L197.86 70.4884Z" fill="url(#paint0_linear_105_8640)"/>
			<path d="M163.99 432.713L163.588 279.446C178.663 290.754 197.016 296.834 215.863 296.766C238.95 296.705 261.068 287.474 277.351 271.108C293.634 254.738 302.747 232.572 302.686 209.484C302.625 186.398 293.396 164.28 277.028 147.997C260.66 131.715 238.493 122.601 215.406 122.662C210.788 122.674 206.364 124.52 203.108 127.794C199.851 131.068 198.028 135.501 198.04 140.119C198.053 144.736 199.899 149.162 203.172 152.417C206.446 155.674 210.879 157.496 215.497 157.484C225.827 157.456 235.934 160.492 244.538 166.209C253.143 171.926 259.859 180.066 263.838 189.599C267.817 199.133 268.879 209.631 266.89 219.768C264.902 229.907 259.952 239.227 252.666 246.55C245.381 253.874 236.088 258.873 225.962 260.915C215.835 262.958 205.33 261.951 195.777 258.023C186.223 254.093 178.046 247.422 172.284 238.846C166.522 230.272 163.433 220.182 163.406 209.852L162.821 67.5391C162.838 65.2381 162.399 62.9564 161.528 60.8264C160.659 58.6961 159.374 56.7596 157.752 55.1287C156.127 53.4978 154.198 52.2048 152.072 51.3245C149.945 50.4442 147.666 49.994 145.364 50.0001C143.065 50.0061 140.787 50.4682 138.666 51.3597C136.544 52.2511 134.622 53.5542 133.006 55.1937C131.392 56.8331 130.118 58.7763 129.26 60.9111C128.4 63.0459 127.973 65.3296 128.001 67.6306L129.171 432.808C129.229 437.395 131.095 441.773 134.364 444.992C137.631 448.211 142.039 450.012 146.626 450C151.214 449.988 155.612 448.164 158.863 444.928C162.115 441.692 163.957 437.3 163.99 432.713Z" fill="url(#paint1_linear_105_8640)"/>
			<defs>
			<linearGradient id="paint0_linear_105_8640" x1="284.866" y1="52.8515" x2="285.688" y2="366.229" gradientUnits="userSpaceOnUse">
				<stop stop-color="#DD1B1B"/>
				<stop offset="0.243" stop-color="#DE1D5B"/>
				<stop offset="0.495" stop-color="#E2254F"/>
				<stop offset="0.751" stop-color="#EA313A"/>
				<stop offset="1" stop-color="#F4431F"/>
			</linearGradient>
			<linearGradient id="paint1_linear_105_8640" x1="215.005" y1="-30.711" x2="216.267" y2="449.816" gradientUnits="userSpaceOnUse">
				<stop stop-color="#1B69DD"/>
				<stop offset="0.243" stop-color="#661DDE"/>
				<stop offset="0.495" stop-color="#8F25E2"/>
				<stop offset="0.751" stop-color="#4B31EA"/>
				<stop offset="1" stop-color="#561FF4"/>
			</linearGradient>
			</defs>
		</svg>

		<p class="text-sm font-medium text-gray-500">
			© 2023 Podiscover<br>
		</p>
	</div>
</div>

app/views/shared/_host_navbar.html.erb
<% if user_signed_in? %>
  <div class="flex items-center">
    <% if current_user.image_url.present? %>
      <%= image_tag current_user.image_url, class: "flex-shrink-0 w-12 h-12 bg-white rounded-full border border-gray-100 shadow-sm" %>
    <% else %>
      <%= image_tag "default.png", class: "flex-shrink-0 w-12 h-12 bg-white rounded-full border border-gray-100 shadow-sm" %>
    <% end %>
    <strong class="hidden ml-4 lg:block"><%= current_user.nickname %></strong>
  </div>
  <hr class="hidden my-4 border-gray-100 lg:block" />
  <div class="fixed bottom-0 left-0 right-0 z-40 flex flex-row justify-between px-2 py-4 mx-0 bg-white shadow lg:relative lg:flex-col lg:bg-transparent rounded-2xl lg:rounded-none lg:shadow-none lg:p-0">
    <div>
      <%= link_to host_podcasts_path, class: current_class?(host_podcasts_path) do %>
        <svg width="32" height="32" viewBox="0 0 32 32" fill="none" xmlns="http://www.w3.org/2000/svg">
        <path d="M16 3C13.4288 3 10.9154 3.76244 8.77759 5.1909C6.63975 6.61935 4.97351 8.64968 3.98957 11.0251C3.00563 13.4006 2.74819 16.0144 3.2498 18.5362C3.75141 21.0579 4.98953 23.3743 6.80762 25.1924C8.6257 27.0105 10.9421 28.2486 13.4638 28.7502C15.9856 29.2518 18.5995 28.9944 20.9749 28.0104C23.3503 27.0265 25.3807 25.3603 26.8091 23.2224C28.2376 21.0846 29 18.5712 29 16C28.9934 12.5542 27.6216 9.25145 25.1851 6.81491C22.7486 4.37837 19.4458 3.00661 16 3V3ZM22.5375 10.7625L19.0375 18.5375C18.9293 18.7626 18.7426 18.9404 18.5125 19.0375L11.0875 22.225C10.9642 22.274 10.8327 22.2994 10.7 22.3C10.434 22.3015 10.178 22.1982 9.98751 22.0125C9.84632 21.8713 9.75062 21.6911 9.71275 21.4951C9.67488 21.299 9.69656 21.0961 9.77501 20.9125L12.9625 13.4875C13.0596 13.2574 13.2374 13.0707 13.4625 12.9625L21.2125 9.4375C21.3996 9.35526 21.6071 9.33155 21.8079 9.36947C22.0087 9.4074 22.1933 9.50519 22.3375 9.65C22.4823 9.79168 22.5793 9.97494 22.6152 10.1743C22.651 10.3737 22.6239 10.5793 22.5375 10.7625V10.7625Z" fill="#000AFF"/>
        </svg>
        <span class="hidden lg:block">Dashboard</span>
      <% end %>
    </div>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<% if user_signed_in? %>
  <div class="flex items-center">
    <% if current_user.image_url.present? %>
      <%= image_tag current_user.image_url, class: "flex-shrink-0 w-12 h-12 bg-white rounded-full border border-gray-100 shadow-sm" %>
    <% else %>
      <%= image_tag "default.png", class: "flex-shrink-0 w-12 h-12 bg-white rounded-full border border-gray-100 shadow-sm" %>
    <% end %>
    <strong class="hidden ml-4 lg:block"><%= current_user.nickname %></strong>
  </div>
  <hr class="hidden my-4 border-gray-100 lg:block" />
  <div class="fixed bottom-0 left-0 right-0 z-40 flex flex-row justify-between px-2 py-4 mx-0 bg-white shadow lg:relative lg:flex-col lg:bg-transparent rounded-2xl lg:rounded-none lg:shadow-none lg:p-0">
    <div>
      <%= link_to root_path, class: current_class?(activities_path) do %>
        <svg class="flex-shrink-0" width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
          <path d="M22.4042 9.57873L13.2376 1.468C12.8996 1.16696 12.4582 1 12.0001 1C11.5421 1 11.1006 1.16696 10.7626 1.468L1.59607 9.57873C1.40839 9.74591 1.2585 9.94929 1.15592 10.1759C1.05334 10.4026 1.00033 10.6475 1.00024 10.8952V21.1703C0.992792 21.6203 1.15597 22.0572 1.45857 22.3975C1.63032 22.5876 1.84189 22.7398 2.07905 22.8437C2.31622 22.9476 2.57349 23.0009 2.83356 22.9999H8.3335C8.57661 22.9999 8.80976 22.9059 8.98167 22.7385C9.15358 22.5711 9.25015 22.3441 9.25015 22.1074V16.7523C9.25015 16.5156 9.34673 16.2886 9.51864 16.1212C9.69054 15.9538 9.9237 15.8598 10.1668 15.8598H13.8334C14.0765 15.8598 14.3097 15.9538 14.4816 16.1212C14.6535 16.2886 14.7501 16.5156 14.7501 16.7523V22.1074C14.7501 22.3441 14.8467 22.5711 15.0186 22.7385C15.1905 22.9059 15.4236 22.9999 15.6667 22.9999H21.1667C21.4708 23.0025 21.7705 22.9296 22.0375 22.788C22.3281 22.6339 22.5707 22.4066 22.7401 22.1298C22.9094 21.8531 22.9992 21.537 23 21.2149V10.8952C22.9999 10.6475 22.9469 10.4026 22.8443 10.1759C22.7417 9.94929 22.5919 9.74591 22.4042 9.57873V9.57873Z" fill="#F06B80"/>
        </svg>
        <span class="hidden lg:block">Feed</span>
      <% end %>
    </div>
    <div>
      <%= link_to user_path(current_user), class: current_class?(user_path(current_user)) do %>
        <svg class="flex-shrink-0" width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
          <path d="M15.5416 16.2736C16.9419 15.3833 18.0188 14.0548 18.6097 12.4888C19.2005 10.9227 19.2733 9.20402 18.8169 7.59229C18.3605 5.98056 17.3999 4.56328 16.0799 3.55445C14.76 2.54561 13.1524 2 11.5 2C9.84759 2 8.24005 2.54561 6.92009 3.55445C5.60014 4.56328 4.63945 5.98056 4.18308 7.59229C3.72672 9.20402 3.79945 10.9227 4.39031 12.4888C4.98116 14.0548 6.05805 15.3833 7.45838 16.2736C5.01678 17.0451 2.84721 18.5169 1.21122 20.5116C1.10002 20.6428 1.02911 20.8041 1.00722 20.9758C0.985338 21.1474 1.01344 21.3217 1.08807 21.4773C1.15891 21.6337 1.27256 21.7661 1.41548 21.8588C1.5584 21.9515 1.72456 22.0005 1.89415 22H21.1058C21.2754 22.0005 21.4416 21.9515 21.5845 21.8588C21.7274 21.7661 21.8411 21.6337 21.9119 21.4773C21.9866 21.3217 22.0147 21.1474 21.9928 20.9758C21.9709 20.8041 21.9 20.6428 21.7888 20.5116C20.1528 18.5169 17.9832 17.0451 15.5416 16.2736Z" fill="#6B90F0"/>
        </svg>
        <span class="hidden lg:block">Profile</span>
      <% end %>
    </div>
    <div>
      <%= link_to users_path, class: current_class?(users_path) do %>
        <svg class="flex-shrink-0" width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
          <path d="M18.651 6.04759C17.2266 3.78997 15.375 1.84711 13.7643 0.251585C13.665 0.154055 13.5436 0.0814887 13.4101 0.039948C13.2767 -0.00159273 13.1352 -0.0109017 12.9974 0.0127987C12.8586 0.0344528 12.7272 0.0892486 12.6146 0.172454C12.502 0.255659 12.4115 0.364773 12.351 0.490372L8.96539 7.52372L5.43739 5.19013C5.24388 5.06324 5.00789 5.01648 4.78 5.05988C4.66694 5.08198 4.5594 5.12596 4.46352 5.18928C4.36763 5.2526 4.2853 5.33403 4.22122 5.42891C2.0847 8.61997 1 11.5071 1 14.0144C1 16.6627 2.062 19.2026 3.95236 21.0753C5.84273 22.9479 8.40662 24 11.08 24C13.7534 24 16.3173 22.9479 18.2076 21.0753C20.098 19.2026 21.16 16.6627 21.16 14.0144C21.16 11.3117 20.3383 8.7068 18.651 6.04759ZM17.5772 15.0129C17.3699 16.3819 16.7249 17.6488 15.7368 18.6276C14.7488 19.6064 13.4699 20.2454 12.088 20.4508H11.9565C11.7366 20.4491 11.5253 20.3657 11.3646 20.2169C11.2039 20.0682 11.1056 19.8651 11.089 19.6478C11.0725 19.4306 11.139 19.2151 11.2753 19.0442C11.4116 18.8732 11.6079 18.7593 11.825 18.725C12.8324 18.5628 13.7627 18.0908 14.4843 17.3759C15.2059 16.6611 15.6823 15.7395 15.8461 14.7416C15.8582 14.6246 15.8942 14.5113 15.9518 14.4086C16.0095 14.3058 16.0876 14.2157 16.1814 14.1437C16.2752 14.0717 16.3829 14.0194 16.4977 13.9898C16.6126 13.9603 16.7323 13.9542 16.8497 13.9718C16.967 13.9895 17.0795 14.0305 17.1803 14.0926C17.2811 14.1546 17.3682 14.2362 17.4362 14.3325C17.5043 14.4289 17.5518 14.5379 17.5761 14.653C17.6003 14.7681 17.6007 14.8868 17.5772 15.0021V15.0129Z" fill="#6BE8F0"/>
        </svg>
        <span class="hidden lg:block">Community</span>
      <% end %>
    </div>
    <div>
      <%= link_to categories_path, class: current_class?(categories_path) do %>
        <svg class="flex-shrink-0" width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
          <path d="M9.19746 2H3.79936C2.8056 2 2 2.8056 2 3.79936V9.19746C2 10.1912 2.8056 10.9968 3.79936 10.9968H9.19746C10.1912 10.9968 10.9968 10.1912 10.9968 9.19746V3.79936C10.9968 2.8056 10.1912 2 9.19746 2Z" fill="#F0BB6B"/>
          <path d="M9.19746 12.7962H3.79936C2.8056 12.7962 2 13.6018 2 14.5956V19.9937C2 20.9874 2.8056 21.793 3.79936 21.793H9.19746C10.1912 21.793 10.9968 20.9874 10.9968 19.9937V14.5956C10.9968 13.6018 10.1912 12.7962 9.19746 12.7962Z" fill="#F0BB6B"/>
          <path d="M19.9936 2H14.5955C13.6017 2 12.7961 2.8056 12.7961 3.79936V9.19746C12.7961 10.1912 13.6017 10.9968 14.5955 10.9968H19.9936C20.9874 10.9968 21.793 10.1912 21.793 9.19746V3.79936C21.793 2.8056 20.9874 2 19.9936 2Z" fill="#F0BB6B"/>
          <path d="M19.9936 12.7962H14.5955C13.6017 12.7962 12.7961 13.6018 12.7961 14.5956V19.9937C12.7961 20.9874 13.6017 21.793 14.5955 21.793H19.9936C20.9874 21.793 21.793 20.9874 21.793 19.9937V14.5956C21.793 13.6018 20.9874 12.7962 19.9936 12.7962Z" fill="#F0BB6B"/>
        </svg>
        <span class="hidden lg:block">Categories</span>
      <% end %>
    </div>
    <div>
      <%= link_to discovers_path, class: current_class?(discovers_path) do %>
        <svg width="23" height="31" viewBox="0 0 23 31" fill="none" xmlns="http://www.w3.org/2000/svg">
        <path d="M22.9745 13.7782C22.9374 13.617 22.8609 13.4675 22.7518 13.3432C22.6427 13.2188 22.5045 13.1235 22.3495 13.0657L15.1495 10.3657L16.9745 1.20317C17.0165 0.990934 16.9894 0.770831 16.8972 0.575125C16.8049 0.379419 16.6524 0.218402 16.462 0.115673C16.2698 0.0133891 16.049 -0.0224564 15.8343 0.0137158C15.6195 0.049888 15.4227 0.156048 15.2745 0.315673L1.27454 15.3157C1.15983 15.4347 1.07682 15.5806 1.03314 15.74C0.989465 15.8995 0.986507 16.0673 1.02454 16.2282C1.06368 16.3885 1.14093 16.537 1.24974 16.661C1.35855 16.785 1.49571 16.881 1.64954 16.9407L8.84954 19.6407L7.02454 28.8032C6.98257 29.0154 7.00969 29.2355 7.10192 29.4312C7.19414 29.6269 7.34664 29.7879 7.53704 29.8907C7.68056 29.9631 7.83879 30.0016 7.99954 30.0032C8.13538 30.0038 8.26988 29.9763 8.39463 29.9225C8.51938 29.8688 8.63169 29.7898 8.72454 29.6907L22.7245 14.6907C22.8393 14.5717 22.9223 14.4257 22.9659 14.2663C23.0096 14.1069 23.0126 13.939 22.9745 13.7782V13.7782Z" fill="#51BD96"/>
        </svg>
        <span class="hidden lg:block">Discover</span>
      <% end %>
    </div>

    <div>
      <%= link_to host_podcasts_path, class: current_class?(host_podcasts_path), target: "_blank" do %>
        <svg width="18" height="24" viewBox="0 0 18 24" fill="none" xmlns="http://www.w3.org/2000/svg">
        <path d="M8.52372 17.1429C9.88769 17.1429 11.1958 16.601 12.1603 15.6366C13.1247 14.6721 13.6666 13.364 13.6666 12V5.14286C13.6666 3.77889 13.1247 2.47078 12.1603 1.50631C11.1958 0.541835 9.88769 0 8.52372 0C7.15975 0 5.85164 0.541835 4.88717 1.50631C3.92269 2.47078 3.38086 3.77889 3.38086 5.14286V12C3.38086 13.364 3.92269 14.6721 4.88717 15.6366C5.85164 16.601 7.15975 17.1429 8.52372 17.1429Z" fill="#C56BF0"/>
        <path d="M16.281 12.0107C16.0567 11.9865 15.832 12.0517 15.6555 12.1921C15.479 12.3325 15.365 12.5368 15.3381 12.7607C15.1499 14.4362 14.3509 15.9837 13.0939 17.1074C11.8369 18.2312 10.2099 18.8524 8.52381 18.8524C6.83772 18.8524 5.21074 18.2312 3.95371 17.1074C2.69668 15.9837 1.89774 14.4362 1.70952 12.7607C1.68263 12.5368 1.56858 12.3325 1.39209 12.1921C1.2156 12.0517 0.990886 11.9865 0.766665 12.0107C0.654284 12.0213 0.545165 12.0543 0.445732 12.1078C0.346298 12.1612 0.258558 12.234 0.187676 12.3218C0.116793 12.4097 0.0641998 12.5108 0.0329911 12.6193C0.00178243 12.7278 -0.00741133 12.8414 0.00595119 12.9535C0.225167 14.8983 1.10575 16.7087 2.5003 18.0818C3.89485 19.4549 5.71874 20.3073 7.66667 20.4964V23.1428C7.66667 23.3701 7.75697 23.5882 7.91772 23.7489C8.07846 23.9097 8.29648 24 8.52381 24C8.75114 24 8.96916 23.9097 9.1299 23.7489C9.29065 23.5882 9.38095 23.3701 9.38095 23.1428V20.4964C11.3289 20.3073 13.1528 19.4549 14.5473 18.0818C15.9419 16.7087 16.8225 14.8983 17.0417 12.9535C17.055 12.8414 17.0458 12.7278 17.0146 12.6193C16.9834 12.5108 16.9308 12.4097 16.8599 12.3218C16.7891 12.234 16.7013 12.1612 16.6019 12.1078C16.5025 12.0543 16.3933 12.0213 16.281 12.0107Z" fill="#C56BF0"/>
        </svg>

        <span class="hidden lg:block">Host</span>
      <% end %>
    </div>

    <div class="hidden admin:block">
      <%= link_to rails_admin_path do %>
        <span class="hidden mt-5 ml-5 text-red-500 lg:block">Admin</span>
      <% end %>
    </div>
  </div>
<% end %>

app/views/shared/_rightbar.html.erb
<div>
  <div>
    <%= render partial: "shared/search_form" %>
  </div>
  <div class="justify-start p-8 mt-5 bg-white rounded-xl">
    <div class="text-lg font-semibold">Podcast of the day</div>
      <div class="flex flex-col items-center mt-5">
        <div class="flex shrink-0">
          <%= link_to podcast_path(podcast) do %>
            <% if podcast.image_urls.any? %>
              <%= image_tag podcast.image_urls.second["url"], class:"rounded-xl" %>
            <% else %>
              <%= image_tag "podiscover.png", class:"rounded-xl" %>
            <% end %>
          <% end %>
        </div>
      </div>
  </div>
</div>

app/views/shared/_search_form.html.erb
<%= form_with(url: search_podcasts_path, method: :get, data: { turbo_frame: "podcasts" }) do |form| %>
  <%= form.text_field :query, placeholder: "Search podcasts", class: "bg-white border-none text-gray-900 rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-4"%>
<% end %>