config/routes.rb
# frozen_string_literal: true

require "sidekiq/web"

Rails.application.routes.draw do
  mount RailsAdmin::Engine => "/admin", :as => "rails_admin"
  authenticate :user, lambda { |u| u.is_admin? } do
    mount Sidekiq::Web => "/sidekiq"
    mount ActiveAnalytics::Engine, at: "analytics"
    mount MaintenanceTasks::Engine => "/maintenance_tasks"
  end

  devise_for :users, controllers: {omniauth_callbacks: "users/omniauth_callbacks"}
  resources :podcasts, only: %i[index show] do
    get :search, on: :collection
    get "subscribers", to: "podcasts#subscribers"
    resources :episodes, only: %i[show index] do
      resources :comments
      patch :like, to: "episodes#like"
      patch :dislike, to: "episodes#dislike"
      patch :marked_as_listened, to: "episodes#marked_as_listened"
      patch :marked_as_unlistened, to: "episodes#marked_as_unlistened"
    end
  end

  resources :dashboard, only: [:index]

  resources :users do
    member do
      get :following, :followers
      get :email_confirmation
      post :allow_email_confirmation
      post :deny_email_confirmation
    end
    collection do
      get :tigers
    end
  end

  resources :relationships, only: %i[create destroy]
  resources :subscriptions, only: %i[index show]
  resources :categories, only: %i[index show]
  resources :activities, only: %i[index], path: "feed"
  resources :discovers, only: %i[index], path: "discover" do
    get :advice, on: :collection
    get :all_responses, on: :collection
  end

  namespace :host do
    resources :podcasts do
      get :episodes
      resources :episodes, only: %i[show index]
    end
  end

  root "home#index"
end

app/models/episode.rb
# frozen_string_literal: true

class Episode < ApplicationRecord
  has_many :episode_image_urls, dependent: :destroy
  belongs_to :podcast
  has_many :comments, dependent: :destroy
  has_many :user_listened_episodes, class_name: "UserListenedEpisode"
  has_many :listeners, through: :user_listened_episodes, source: :user

  def language_emoji
    if language.include?("en")
      "🇬🇧"
    elsif language.include?("tr")
      "🇹🇷"
    elsif language.include?("de")
      "🇩🇪"
    elsif language.include?("se")
      "🇸🇪"
    else
      "🌐"
    end
  end

  def listed_by?(user)
    listeners.where(id: user.id).any?
  end
end

app/controllers/episodes_controller.rb
# frozen_string_literal: true

class EpisodesController < ApplicationController
  include ActionView::RecordIdentifier
  before_action :authenticate_user!, only: [:index]

  def index
    @podcast = Podcast.find(params[:podcast_id])
    sorted_episodes = @podcast.episodes.sort_by { |e| e.release_date.to_date }.reverse
    @pagy, @episodes = pagy_array(sorted_episodes, items: 30)
  end

  def show
    @podcast = Podcast.find(params[:podcast_id])
    @episode = @podcast.episodes.find(params[:id])
  end

  def like
    @episode = Episode.find(params[:episode_id])

    @episode.increment!(:likes)
    Activity.create!(activatable: Likeable.new(podcast_id: @episode.podcast.id, episode_id: @episode.id, action: "liked"), user_id: current_user.id)

    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: turbo_stream.replace(
          "#{dom_id(@episode)}_likes",
          partial: "episodes/likes",
          locals: {episode: @episode, action: "dislike"}
        )
      end
    end
  end

  def dislike
    @episode = Episode.find(params[:episode_id])

    @episode.decrement!(:likes)
    Activity.create!(activatable: Likeable.new(podcast_id: @episode.podcast.id, episode_id: @episode.id, action: "disliked"), user_id: current_user.id)

    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: turbo_stream.replace(
          "#{dom_id(@episode)}_likes",
          partial: "episodes/likes",
          locals: {episode: @episode, action: "like"}
        )
      end
    end
  end

  def marked_as_listened
    @episode = Episode.find(params[:episode_id])

    UserListenedEpisode.create!(user_id: current_user.id, episode_id: @episode.id) unless @episode.listed_by?(current_user)

    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: turbo_stream.replace(
          "#{dom_id(@episode)}_listens",
          partial: "episodes/listens",
          locals: {episode: @episode, action: "unlistened"}
        )
      end
    end
  end

  def marked_as_unlistened
    @episode = Episode.find(params[:episode_id])

    UserListenedEpisode.find_by(user_id: current_user.id, episode_id: @episode.id).destroy if @episode.listed_by?(current_user)

    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: turbo_stream.replace(
          "#{dom_id(@episode)}_listens",
          partial: "episodes/listens",
          locals: {episode: @episode, action: "listened"}
        )
      end
    end
  end
end

app/controllers/host/episodes_controller.rb
# frozen_string_literal: true

module Host
  class EpisodesController < ApplicationController
    layout "host"

    before_action :authenticate_user!
    before_action :check_host

    def show
      podcast = Podcast.find(params[:podcast_id])
      @episode = podcast.episodes.find(params[:id])
    end

    private

    def check_host
      redirect_to root_path unless current_user.host?
    end
  end
end

app/helpers/host/episode_helper.rb
module Host
  module EpisodeHelper
    def sort_link(column:, label:)
      if column == params[:column]
        link_to(label, host_podcast_episodes_path(column: column, direction: next_direction))
      else
        link_to(label, host_podcast_episodes_path(column: column, direction: "asc"))
      end
    end

    def next_direction
      (params[:direction] == "asc") ? "desc" : "asc"
    end
  end
end

app/views/episodes/_dislikes.html.erb
<%= turbo_frame_tag "#{dom_id(episode)}_dislikes" do %>
	DISLIKE
	<%= button_to 'Dislike!',
				podcast_episode_dislike_path(episode.podcast, episode),
				method: :patch, data: { turbo_frame: '_top' } %>
<% end %>

app/views/episodes/_episode.html.erb
<div class="flex p-4 mb-5 bg-white rounded-xl" id="<%= dom_id episode %>">
	<div>
		<%= link_to podcast_episode_path(episode.podcast, episode) do %>
			<% if episode.episode_image_urls.any? %>
				<%= image_tag episode.episode_image_urls.last.url, class:"rounded" %>
			<% else %>
				<%= image_tag "podiscover.png", class:"rounded" %>
			<% end %>
		<% end %>
	</div>
	<div class="flex justify-between w-full">
		<div class="flex flex-col justify-around ml-5">
			<div class="text-sm font-medium"><%= episode.name %></div>
			<div class="text-sm font-medium text-gray-500"><%= episode.release_date.to_date %></div>
		</div>
		<div class="flex">
			<div class="flex items-center mr-5">
				<% last_likeable = current_user.activities.where(activatable_type: "Likeable").last&.likeable %>
				<% if last_likeable && last_likeable.episode_id == episode.id && last_likeable.action == 'liked' %>
					<%= render partial: 'episodes/likes', locals: { episode: episode, action: 'dislike' } %>
				<% else %>
					<%= render partial: 'episodes/likes', locals: { episode: episode, action: 'like' } %>
				<% end %>
			</div>
			<div class="flex items-center">
				<%= image_tag "comments_icon.svg", class:"mx-auto mr-2" %>
				<%= episode.comments.count %>
			</div>
		</div>
	</div>
</div>

app/views/episodes/_likes.html.erb
<div>
	<%= turbo_frame_tag "#{dom_id(episode)}_likes", class: "flex items-center" do %>
		<div>
			<% if action == 'like' %>
				<%= button_to image_tag("thumps_up.svg"), podcast_episode_like_path(episode.podcast, episode), method: :patch, data: { turbo_frame: '_top' }, class:"mx-auto mr-2" %>
			<% else %>
				<%= button_to image_tag("thumps_up_colored.svg"), podcast_episode_dislike_path(episode.podcast, episode), method: :patch, data: { turbo_frame: '_top' }, class:"mx-auto mr-2" %>
			<% end %>
		</div>
		<div><%= episode.likes %></div>
	<% end %>
</div>

app/views/episodes/_listens.html.erb
<div>
	<%= turbo_frame_tag "#{dom_id(episode)}_listens", class: "flex items-center" do %>
		<div>
			<% if action == 'unlistened' %>
				<%= button_to image_tag("marked_as_unlistened_icon.svg"), podcast_episode_marked_as_unlistened_path(episode.podcast, episode), method: :patch, data: { turbo_frame: '_top' } %>
			<% else %>
				<%= button_to image_tag("mark_as_listened_icon.svg"), podcast_episode_marked_as_listened_path(episode.podcast, episode), method: :patch, data: { turbo_frame: '_top' }, class:"mx-auto mr-2" %>
			<% end %>
		</div>
	<% end %>
</div>

app/views/episodes/index.html.erb
<div class="w-full">
  <div class="flex items-center justify-between mb-8">
	  <h1 class="text-4xl font-bold"><%= link_to @podcast.name, podcast_path(@podcast), class: "text-red-600" %> Episodes</h1>
  </div>

  <% if @episodes.empty? %>
    <div class="flex flex-col items-center justify-center p-12 bg-white rounded-xl">
      <p class="text-gray-500">😳 You need to follow some people to see their podcasts</p>
      <%= image_tag "not-found.svg", class:"my-12" %>
      <%=  link_to 'Find some cool people 🥳', users_path, class:"bg-primary text-white rounded-full px-6 py-2" %>
    </div>
  <% end %>

  <%= turbo_stream_from "episodes" %>
  <div id="episodes" class="divide-y">
  </div>

  <%= turbo_frame_tag "pagination", src: podcast_episodes_path(@podcast, format: :turbo_stream), loading: :lazy do %>
	<div class="flex items-center justify-center mt-10">
	  <% unless @episodes.empty? %>
		<%= image_tag "spinner.gif" %>
	  <% end %>
	</div>
  <% end %>
</div>

app/views/episodes/index.turbo_stream.erb
<%= turbo_stream.append "episodes" do %>
  <%= render partial: "episodes/episode", collection: @episodes %>
<% end %>

<% unless @pagy.page == @pagy.last %>
  <%= turbo_stream.replace "pagination" do %>
    <%= turbo_frame_tag "pagination", src: podcast_episodes_path(page: @pagy.next, format: :turbo_stream), loading: :lazy %>
  <% end %>
<% end %>

app/views/episodes/show.html.erb
<%  content_for :og_header do %>
  <%= tag(:meta, name: "twitter:card", content: "summary") %>
  <%= tag(:meta, name: "twitter:title", content: @episode.podcast.name) %>
  <%= tag(:meta, name: "twitter:description", content: @episode.html_description) %>
  <%= tag(:meta, name: "twitter:image", content: @episode.episode_image_urls.second.url) %>
  <%= tag(:meta, property: "og:title", content: @episode.podcast.name) %>
  <%= tag(:meta, property: "og:description", content: @episode.html_description) %>
  <%= tag(:meta, property: "og:image", content: @episode.episode_image_urls.second.url) %>
  <%= tag(:meta, property: "og:url", content: podcast_episode_url(@episode.podcast, @episode)) %>
<% end %>

<div class="flex flex-row">
  <div class="mb-5 lg:w-3/4 divide-slate-200">
      <div class="justify-start p-8 bg-white rounded-xl">
        <div class="flex flex-col">
          <div class="flex flex-col sm:flex-row">
            <div class="flex flex-col items-center shrink-0">
              <% if @episode.episode_image_urls.any? %>
                <%= image_tag @episode.episode_image_urls.second.url, class:"rounded-xl" %>
              <% else %>
                <%= image_tag "podiscover.png", class:"rounded-xl" %>
              <% end %>
            </div>
            <div class="flex flex-col ml-0 sm:ml-5">
              <div class="text-3xl font-extrabold"><%= @episode.podcast.name %></div>
              <div class="mt-1 text-xl font-bold text-gray-500"><%= @episode.name %></div>
              <div class="mt-8 text-sm font-medium leading-relaxed text-gray-500"><%= sanitize @episode.html_description %></div>
              <div class="mt-5">
                <% @podcast.categories.each do |category| %>
                  <%= render(CategoriesComponent.new(name: category.name)) %>
                <% end %>
              </div>
            </div>
          </div>
          <div>
            <% if action_name == "show" %>
              <%= link_to @episode.external_urls, class: "flex items-center mt-5", target: "_blank" do %>
                <%= image_tag "spotify_logo.png", class: "ml-5 w-8 h-8" %>
                <span class="ml-2 bg-transparent text-[#1db954] font-semibold">See on Spotify</span>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>

		<div class="flex items-center p-8 my-5 bg-white rounded-xl">
			<div class="flex items-center mr-5">
        <% if current_user %>
          <% last_likeable = current_user.activities.where(activatable_type: "Likeable").last&.likeable %>
          <% if last_likeable && last_likeable.episode_id == @episode.id && last_likeable.action == 'liked' %>
            <%= render partial: 'episodes/likes', locals: { episode: @episode, action: 'dislike' } %>
          <% else %>
            <%= render partial: 'episodes/likes', locals: { episode: @episode, action: 'like' } %>
          <% end %>
        <% end %>
			</div>
			<div class="flex items-center">
				<%= image_tag "comments_icon.svg", class:"mx-auto mr-2" %>
				<%= @episode.comments.count %>
			</div>
      <% if current_user &&  %>
        <div class="relative flex items-center ml-5 bottom-[-4px]">
          <% if @episode.listed_by?(current_user) %>
            <%= render partial: 'episodes/listens', locals: { episode: @episode, action: 'unlistened' } %>
          <% else %>
            <%= render partial: 'episodes/listens', locals: { episode: @episode, action: 'listened' } %>
          <% end %>
        </div>
      <% end %>
		</div>
    <% if current_user %>
      <div class="flex p-8 my-5 bg-white rounded-xl">
        <%= render partial: 'comments/form', locals: { comment: Comment.new, podcast: @episode.podcast, episode: @episode } %>
      </div>
    <% end %>
    <% if @episode.comments.any? %>
      <% @episode.comments.each do |comment| %>
        <div class="flex flex-col p-8 my-5 bg-white rounded-xl">
          <div class="flex items-center justify-between w-full">
            <div class="flex items-center">
              <% if comment.user.image_url.present? %>
                <%= image_tag comment.user.image_url, class: "flex-shrink-0 w-12 h-12 bg-white rounded-full border border-gray-100 shadow-sm mr-5" %>
              <% else %>
                <%= image_tag "default.png", class: "flex-shrink-0 w-12 h-12 bg-white rounded-full border border-gray-100 shadow-sm mr-5" %>
              <% end %>
              <span class="text-base font-bold"><%= comment.user.nickname %></span>
            </div>
            <span class="text-xs font-normal text-gray-500"><%= comment.created_at.to_date %></span>
          </div>
          <div class="ml-16 text-base font-normal text-gray-700">
            <%= comment.body %>
            <div class="mt-5">
              <a type="button" class="text-white bg-[#1da1f2] hover:bg-[#1da1f2]/90 focus:ring-4 focus:outline-none focus:ring-[#1da1f2]/50 font-medium rounded-lg text-sm px-5 py-2.5 text-center inline-flex items-center dark:focus:ring-[#1da1f2]/55 mr-2 mb-2 mt-2" href="https://twitter.com/intent/tweet?text=<%= comment.body %>&amp;url=<%= podcast_episode_url(comment.episode.podcast, comment.episode) %>&amp;via=podiscoverme">
                <svg class="w-4 h-4 mr-2 -ml-1" aria-hidden="true" focusable="false" data-prefix="fab" data-icon="twitter" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path fill="currentColor" d="M459.4 151.7c.325 4.548 .325 9.097 .325 13.65 0 138.7-105.6 298.6-298.6 298.6-59.45 0-114.7-17.22-161.1-47.11 8.447 .974 16.57 1.299 25.34 1.299 49.06 0 94.21-16.57 130.3-44.83-46.13-.975-84.79-31.19-98.11-72.77 6.498 .974 12.99 1.624 19.82 1.624 9.421 0 18.84-1.3 27.61-3.573-48.08-9.747-84.14-51.98-84.14-102.1v-1.299c13.97 7.797 30.21 12.67 47.43 13.32-28.26-18.84-46.78-51.01-46.78-87.39 0-19.49 5.197-37.36 14.29-52.95 51.65 63.67 129.3 105.3 216.4 109.8-1.624-7.797-2.599-15.92-2.599-24.04 0-57.83 46.78-104.9 104.9-104.9 30.21 0 57.5 12.67 76.67 33.14 23.72-4.548 46.46-13.32 66.6-25.34-7.798 24.37-24.37 44.83-46.13 57.83 21.12-2.273 41.58-8.122 60.43-16.24-14.29 20.79-32.16 39.31-52.63 54.25z"></path></svg>
                Share on Twitter
              </a>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="hidden w-1/4 ml-10 lg:block">
    <%= render partial: 'shared/rightbar', locals: { podcast: today_podcast } %>
  </div>
</div>