config/routes.rb
# frozen_string_literal: true

require "sidekiq/web"

Rails.application.routes.draw do
  mount RailsAdmin::Engine => "/admin", :as => "rails_admin"
  authenticate :user, lambda { |u| u.is_admin? } do
    mount Sidekiq::Web => "/sidekiq"
    mount ActiveAnalytics::Engine, at: "analytics"
    mount MaintenanceTasks::Engine => "/maintenance_tasks"
  end

  devise_for :users, controllers: {omniauth_callbacks: "users/omniauth_callbacks"}
  resources :podcasts, only: %i[index show] do
    get :search, on: :collection
    get "subscribers", to: "podcasts#subscribers"
    resources :episodes, only: %i[show index] do
      resources :comments
      patch :like, to: "episodes#like"
      patch :dislike, to: "episodes#dislike"
      patch :marked_as_listened, to: "episodes#marked_as_listened"
      patch :marked_as_unlistened, to: "episodes#marked_as_unlistened"
    end
  end

  resources :dashboard, only: [:index]

  resources :users do
    member do
      get :following, :followers
      get :email_confirmation
      post :allow_email_confirmation
      post :deny_email_confirmation
    end
    collection do
      get :tigers
    end
  end

  resources :relationships, only: %i[create destroy]
  resources :subscriptions, only: %i[index show]
  resources :categories, only: %i[index show]
  resources :activities, only: %i[index], path: "feed"
  resources :discovers, only: %i[index], path: "discover" do
    get :advice, on: :collection
    get :all_responses, on: :collection
  end

  namespace :host do
    resources :podcasts do
      get :episodes
      resources :episodes, only: %i[show index]
    end
  end

  root "home#index"
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :user
  belongs_to :podcast

  after_create_commit { broadcast_append_to "subscriptions" }
  after_destroy_commit { broadcast_remove_to "subscriptions" }
end

app/controllers/subscriptions_controller.rb
# frozen_string_literal: true

class SubscriptionsController < ApplicationController
  before_action :authenticate_user!

  def index
    subscriptions = current_user.feed.uniq { |s| s.podcast_id }
    sorted_subscriptions = subscriptions.sort_by { |s| s.podcast.users.count }.reverse
    @pagy, @subscriptions = pagy_array(sorted_subscriptions, items: 30)
  end

  def show
    @subscription = current_user.subscriptions.find(params[:id])
  end
end

app/helpers/subscriptions_helper.rb
# frozen_string_literal: true

module SubscriptionsHelper
  def podcast_middle_image_url(subscription)
    subscription.podcast.image_urls.second["url"]
  end

  def podcast_listeners_count(subscription)
    subscription.podcast.users.count
  end
end

app/views/subscriptions/_subscription.html.erb
<div id="<%= dom_id subscription %>" class="p-4 transition-all bg-white hover:shadow hover:-translate-y-1 rounded-xl">
  <%= link_to(subscription.podcast) do %>
    <div class="grid content-around gap-4 grid-row-2">
      <div class="rounded-xl">
        <% if subscription.podcast.image_urls.any? %>
          <%= image_tag podcast_image(subscription), class:"rounded-xl" %>
        <% else %>
          <%= image_tag "podiscover.png", class:"rounded-xl" %>
        <% end %>
      </div>
      <div>
        <div class="text-lg">
          <%= subscription.podcast.name %>
        </div>
        <div class="text-xs font-medium text-gray-400">
          <%= subscription.podcast.episodes.count %> Current Episodes
        </div>
      </div>
    </div>
  <% end %>

  <% if controller_name == "subscriptions" %>
    <div class="mt-3 text-xs font-thin">
      <% if subscription.podcast.users.count > 1 %>
        <span class="text-blue-500"><%= pluralize subscription.podcast.users.count, "person" %></span> subscribe this podcast
      <% else %>
        <%= link_to subscription.user.nickname, subscription.user, class: "text-blue-500" %> subscribes
      <% end %>
    </div>
  <% end %>
</div>

app/views/subscriptions/index.html.erb
<div class="flex flex-row">
  <div class="mb-5 lg:w-3/4 divide-slate-200">
    <div class="mb-4">
      <h1 class="text-4xl font-bold">Subscriptions</h1>
    </div>

    <% if @subscriptions.empty? %>
      <div class="flex flex-col items-center justify-center p-12 bg-white rounded-xl">
        <p class="text-gray-500">😳 You need to follow some people to see their podcasts</p>
        <%= image_tag "not-found.svg", class:"my-12" %>
        <%=  link_to 'Find some cool people 🥳', users_path, class:"bg-primary text-white rounded-full px-6 py-2" %>
      </div>
    <% end %>

    <%= turbo_stream_from "activities" %>
    <div id="subscriptions" class="grid gap-4 2xl:grid-cols-4 xl:grid-cols-3 lg:grid-cols-2">
    </div>
    <%= turbo_frame_tag "pagination", src: subscriptions_path(format: :turbo_stream), loading: :lazy do %>
      <div class="flex items-center justify-center mt-10">
        <% unless @subscriptions.empty? %>
          <%= image_tag "spinner.gif" %>
        <% end %>
      </div>
    <% end %>
  </div>

  <div class="hidden w-1/4 ml-10 lg:block">
    <%= render partial: 'shared/rightbar', locals: { podcast: today_podcast } %>
  </div>
</div>

app/views/subscriptions/index.turbo_stream.erb
<%= turbo_stream.append "subscriptions" do %>
  <%= render partial: "subscriptions/subscription", collection: @subscriptions %>
<% end %>

<% unless @pagy.page == @pagy.last %>
  <%= turbo_stream.replace "pagination" do %>
    <%= turbo_frame_tag "pagination", src: subscriptions_path(page: @pagy.next, format: :turbo_stream), loading: :lazy %>
  <% end %>
<% end %>

app/views/subscriptions/show.html.erb
<div class="flex w-full mx-auto">
  <div>
    <div class="flex flex-col items-center justify-start my-5 sm:flex-row">
        <% if subscription.podcast.image_urls.any? %>
          <%= image_tag podcast_middle_image_url(subscription), class: "object-cover h-48 w-96" %>
        <% else %>
          <%= image_tag "podiscover_medium.png", class: "object-cover h-48 w-96" %>
        <% end %>  
      <% if action_name == "show" %>
        <%= link_to  @subscription.podcast.external_url, class: "flex items-center" do %>
          <%= image_tag "spotify_logo.png", class: "ml-5 w-8 h-8" %>
          <span class="ml-2 bg-transparent text-[#1db954] font-semibold">See on Spotify</span>
        <% end %>      
      <% end %>
    </div>

    <p class="my-5">
      <strong class="block mb-1 font-medium">Name:</strong>
      <%= @subscription.podcast.name %>
    </p>

    <p class="my-5">
      <strong class="block mb-1 font-medium">Publisher:</strong>
      <%= @subscription.podcast.publisher %>
    </p>  

    <p class="my-5">
      <strong class="block mb-1 font-medium">Description:</strong>
      <%= @subscription.podcast.description %>
    </p>

    <p class="my-5">
      <% if @subscription.podcast.users.count > 1 %>
        <strong class="block mb-1 font-medium">Subscribers:</strong>
        <% @subscription.podcast.users.each_with_index do |listener, index| %>
          <%= link_to listener.nickname, listener, class: "text-blue-500" %>
          <% unless podcast_listeners_count(@subscription)-1 == index %>
            <%= " and " %>
          <% end %>
        <% end %>
      <% else %>
        <strong class="block mb-1 font-medium">Subscriber:</strong> <%= link_to @subscription.user.nickname, @subscription.user, class: "text-blue-500" %>
      <% end %>
    </p>

    <% if @subscription.podcast.categories.any? %>
      <p class="my-5">
        <strong class="block mb-1 font-medium">Categories:</strong>
        <%= @subscription.podcast.categories.each do %>
          <%= link_to @category.name, category_path(@category), class: "text-blue-500" %>
        <% end %>
      </p>
    <% end %>
    
    <%= link_to 'Back to podcasts', subscriptions_path, class: "font-medium" %>
  </div>
</div>